project_id = "rvtsfnaqlnggfkoqygbm"

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-reset-password]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.custom-signup]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.resend-confirmation]
verify_jwt = false

[functions.cleanup-expired-confirmations]
verify_jwt = false

[functions.confirm-email]
verify_jwt = false

[functions.redirect-confirm]
verify_jwt = false

[functions.redirect-recovery]
verify_jwt = false

[functions.reset-redirect]
verify_jwt = false

[functions.optimize-job-title]
verify_jwt = false

[functions.parse-job-search]
verify_jwt = false

[auth]
enable_signup = false
enable_confirmations = false